spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yongle?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    port: 6379
    database: 0
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8716/eureka